/*   Messages for the ESCR library and associated applications.
/*
msg err1
  lan english -def
    Unable to create new memory context.
msg err2
  lan english -def
    Unable to allocate dynamic memory of %p1i bytes.
msg err3
  lan english -def
    The maximum versions of symbol "%p2s" already exist on attempt to
    create a new version.
msg err4
  lan english -def
    Symbol "%p1s" not found.
msg err5
  lan english -def
    Unexpected end of input encountered.
msg err6
  lan english -def
    Command "%p1s" is unrecognized.
msg err7
  lan english -def
    Symbol "%p1s" is not a command as expected.
msg err8
  lan english -def
    Label "%p1s" was not found.
msg err9
  lan english -def
    Symbol "%p1s" is not a label.
msg err10
  lan english -def
    In nested input file at end of block.
msg err11
  lan english -def
    No output file exists on attempt to write to it.
msg err12
  lan english -def
    No output file exists on attempt to close it.
msg err13
  lan english -def
    Attempt to close the preprocessor output file.
msg err14
  lan english -def
    Bad input line.
msg err15
  lan english -def
    Starting string for syntax range is empty.
msg err16
  lan english -def
    No end (%p2s) for syntax exclusion start (%p1s) in column %p3i.
msg err17
  lan english -def
    Missing end for script comment started in column %p1s.
msg err18
  lan english -def
    End of function "%p1s" not found.
msg err19
  lan english -def
    No such function "%p1s".
msg err20
  lan english -def
    Symbol "%p1s" is not a function.
msg err21
  lan english -def
    Symbol "%p1s" does not have a value (not a variable or constant).
msg err22
  lan english -def
    String "%p1s" can not be interpreted as a value.
msg err23
  lan english -def
    A required command parameter is missing.
msg err24
  lan english -def
    The term "%p1s" can not be converted to BOOL type.
msg err25
  lan english -def
    The term "%p1s" can not be converted to INTEGER type.
msg err26
  lan english -def
    The term "%p1s" can not be converted to TIME type.
msg err27
  lan english -def
    The term  "%p1s"can not be converted to REAL type.
msg err28
  lan english -def
    The term "%p1s" can not be converted to INTEGER or REAL type.
msg err29
  lan english -def
    Parameter "%p1s" to command "%p2s" is unrecognized.
msg err30
  lan english -def
    "%p1s" is not the name of data type.
msg err31
  lan english -def
    Too many command parameters found.  The first unexpected parameter was "%p1s".
msg err32
  lan english -def
    The string "%p1s" is not one character long.  Only a one-character
    string is allowe here.
msg err33
  lan english -def
    A required parameter to function "%p1s" is missing.
msg err34
  lan english -def
    Too many parameters to function "%p2s".  The first unexpected parameter was "%p1s".
msg err35
  lan english -def
    The data type of term "%p1s" is incompatible with its usage here.
msg err36
  lan english -def
    Attempt to divide by zero.
msg err37
  lan english -def
    Attempt to take the square root of a negative value.
msg err38
  lan english -def
    Non-integer exponent to negative value.
msg err39
  lan english -def
    Attempt to get logarithm of a non-positive value.
msg err40
  lan english -def
    Date-modifying parameter %p1s to DATE function after date computed.
msg err41
  lan english -def
    Parameter "%p1s" to function "%p2s" is unrecognized.
