/*   Messages for the ESCR library and associated applications.
/*
msg err1
  lan english -def
    Unable to create new memory context.
msg err2
  lan english -def
    Unable to allocate dynamic memory of %p1i bytes.
msg err3
  lan english -def
    The maximum versions of symbol "%p2s" already exist on attempt to
    create a new version.
msg err4
  lan english -def
    Symbol "%p1s" not found.
msg err5
  lan english -def
    Unexpected end of input encountered.
msg err6
  lan english -def
    Command "%p1s" is unrecognized.
msg err7
  lan english -def
    Symbol "%p1s" is not a command as expected.
msg err8
  lan english -def
    Label "%p1s" was not found.
msg err9
  lan english -def
    Symbol "%p1s" is not a label.
msg err10
  lan english -def
    In nested input file at end of block.
msg err11
  lan english -def
    No output file exists on attempt to write to it.
msg err12
  lan english -def
    No output file exists on attempt to close it.
msg err13
  lan english -def
    Attempt to close the preprocessor output file.
msg err14
  lan english -def
    Bad input line.
